### ISSUE TITLE
[Part A, ch.8] - Code refactory

### ISSUE THREAD

**Issue by jordrag** [braboj/tutorial-python#33]
Paragraph 8.19. Function Introspection code needs a little refactoring: a regular parameter like c=20 can't be after other with "*", and should be displaced. There are no "__kwdefaults" and "__annotations" parameters in "foo" function.

**Comment by braboj** [comment]
> Paragraph 8.17. Function Introspection code needs a little refactoring: 

- Change the paragraph in the issue comment (shall be 8.19)

> a regular parameter like c=20 can't be after other with "*", and should be displaced.

- It is possible in Python 3.10, but the code must be change to make it compatible with Python 2

> There are no "__kwdefaults" and "__annotations" parameters in "foo" function.
- Yes, please make a commit and create a pull request.
