### ISSUE TITLE
Single line code highlight

### ISSUE THREAD

**Issue by Vasc01** [braboj/tutorial-python#4]
Code surrounded by apostrophes is not highlighted as expected when the document is exported as PDF.
![code highlight](https://github.com/braboj/tutorial-python/assets/106252560/2da0c746-1ab8-4901-8e9c-6b2108e195cd)

**Comment by braboj** [comment]
Closed by accident

**Comment by braboj** [comment]
The issue seems to be only valid for pdf documents. Another tool may solve the problem.
