### ISSUE TITLE
[Part B, Ch. 2] - Review and change example code

### ISSUE THREAD

**Issue by Vasc01** [braboj/tutorial-python#42]
2.1. Single Responsibility Principle

- examples single_responsibility_bad.py and single_responsibility_good.py

2.2. Open/Closed Principle

- examples open_closed_bad.by and open_closed_good.by

2.5. Dependency Inversion Principle

- in file dependency_inversion_good.py make MathAbc an abstract class

**Comment by braboj** [comment]
Done, but for 2.5 we will not use abstract classes as they are a little bit more specific and require knowledge about the `six` library.
The problem is due to the incompatibility when using metaclasses, required by the `abc` module.
